version: "3.7"
name: course-work

services:
  app:
    build:
      args:
        user: test
        uid: 1000
      context: ./app
      dockerfile: Dockerfile
    container_name: course-work.app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ../:/var/www
    networks:
      - course-work

  db:
    image: mysql:8.0
    container_name: course-work.db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - course-work
    volumes:
      - mysql-data:/var/lib/mysql

  nginx:
    image: nginx:alpine
    container_name: course-work.nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ../:/var/www
      - ./nginx:/etc/nginx/conf.d/
    networks:
      - course-work

networks:
  course-work:
    driver: bridge

volumes:
  mysql-data: